composeexample/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('djangolist.urls',namespace='djangolist')),
]

djangolist/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url 
from .views import ProductListView, ProductListInfiniteView
app_name = 'djangolist'
urlpatterns = [
    path('', ProductListInfiniteView.as_view(), name='infinitescroll'),
    path('listing/', ProductListView.as_view(),name="productlist"),
    
]

djangolist/models.py
from django.db import models

# Create your models here.
class Category(models.Model):
    name =  models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=40)
    category = models.ForeignKey(Category,on_delete= models.CASCADE)
    quantity = models.IntegerField(default=0)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.name

djangolist/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Product
from .filters import ProductFilter
# Create your views here.

class FilteredListView(ListView):
    filterset_class = None

    def get_queryset(self):
        # Get the queryset however you usually would.  For example:
        queryset = super().get_queryset()
        # Then use the query parameters and the queryset to
        # instantiate a filterset and save it as an attribute
        # on the view instance for later.
        self.filterset = self.filterset_class(self.request.GET, queryset=queryset)
        # Return the filtered queryset
        return self.filterset.qs.distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Pass the filterset to the template - it provides the form.
        context['filterset'] = self.filterset
        return context

class ProductListView(FilteredListView):
    template_name = "djangolist/my_product_list.html"
    model = Product
    filterset_class = ProductFilter
    paginate_by = 10


class ProductListInfiniteView(FilteredListView):
    template_name = "djangolist/infinite_product_list.html"
    model = Product
    paginate_by = 3
    context_object_name = "products"
    filterset_class = ProductFilter

djangolist/templates/djangolist/base.html
<!doctype html>
<html lang="en">
  <head>
    <title>{%block title%}Default Title{%endblock%}</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
  </head>
  <body>
    <div class="container-fluid">
      <nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
        <a class="navbar-brand"  href="{% url 'djangolist:infinitescroll' %}">Django Listing</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'djangolist:infinitescroll' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link"  href="{% url 'djangolist:productlist' %}">Listing</a>
            </li>
          </ul>
        </div>
      </nav>
    {%block content%}

    {%endblock%}
  </div>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

    {%block otherscripts%}
    {%endblock%}
  </body>
</html>

djangolist/templates/djangolist/infinite_product_list.html
{%extends 'djangolist/base.html'%}
{% load static %}
{% load customtags %}
{% load crispy_forms_tags %}
{%block title%}Infinite Scorlling Example{%endblock%}
{%block content %}
<h5>Proudcts</h5>
<div class="row">
  <div class="col">
    <h5>Search Criteria:</h5>
    <form method="get">
      {{ filterset.form|crispy }}
      <div class="row mt-2">
        <div class="col">
          <input class="btn btn-primary" type="submit" />
        </div>
      </div>
    </form>
  </div>
</div>
<table class="table table-bordered border-primary table-striped table-hover infinite-container">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Category</th>
      <th scope="col">Quantity</th>
    </tr>
  </thead>
  <tbody>
    {% for product in products %}
    <tr class="infinite-item">

    <td>{{product.name}}</td>
    <td>{{product.category}}</td>
    <td>{{product.quantity}}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% if page_obj.has_next %}
<a class="infinite-more-link" href="?{% param_replace page=page_obj.next_page_number %}">More</a>
{% endif %}
<div class="loading infinite-loading" style="display: none;">
  Loading...
</div>

{%endblock%}

{%block otherscripts%}
<script src="{% static 'djangolist/javascripts/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'djangolist/javascripts/infinite.min.js' %}"></script>
<script>
  $(document).ready(function () {
    var infinite = new Waypoint.Infinite({
      element: $('.infinite-container')[0],
      onBeforePageLoad: function () {
        $('.loading').show();
      },
      onAfterPageLoad: function ($items) {
        $('.loading').hide();
      }
    });
  });

</script>
{%endblock%}

djangolist/templates/djangolist/my_product_list.html
{%extends "djangolist/base.html"%}
{% load customtags %}
{% load crispy_forms_tags %}
{%block title%}Django Listing with Filtering{%endblock%}
{%block content%}
<div class="card">
  <div class="card-header">
      <h5>Products</h5>
  </div>
  <div class="card-body">
    <div class="row">
      <div class="col">
        <h5>Search Criteria:</h5>
        <form method="get">
          {{ filterset.form|crispy }}
          <div class="row mt-2">
            <div class="col">
              <input class="btn btn-primary" type="submit" />
            </div>
          </div>
        </form>
      </div>
    </div>
    <div class="row">
      <div class="col">
        <h5>Product List</h5>
        <table class="table table-bordered border-primary table-striped table-hover">
          <thead>
            <tr>
              <th scope="col">Name</th>
              <th scope="col">Category</th>
              <th scope="col">Quantity</th>
            </tr>
          </thead>
          <tbody>
            {% for obj in object_list%}
            <tr>
    
              <td>{{obj.name}}</td>
              <td>{{obj.category}}</td>
              <td>{{obj.quantity}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        {% if is_paginated %}
        <nav aria-label="Page navigation example">
          <ul class="pagination">
            <li class="page-item {%if page_obj.number == 1 %} disabled {%endif%}">
              <a class="page-link" href="?{% param_replace page=1 %}" aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
              </a>
            </li>
            {% for i in paginator.num_pages|times%}
            <li class="page-item {%if i|add:'1' == page_obj.number %} active {%endif%}"><a class="page-link"
                href="?{% param_replace page=i|add:'1' %}">{{i|add:"1"}}</a></li>
            {%endfor%}
    
    
            <li class="page-item {%if page_obj.number == paginator.num_pages %} disabled {%endif%}">
              <a class="page-link" href="?{% param_replace page=paginator.num_pages %}" aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
              </a>
            </li>
          </ul>
        </nav>
        {% endif %}
      </div>
    </div>
  </div>
</div>


{%endblock%}